//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.ATR.WinUIAutomationRuntimeWrapper.Logging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InformationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infosys.ATR.WinUIAutomationRuntimeWrapper.Logging.InformationMessages", typeof(InformationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Entered Automation RunTime Wrapper||Class:{0}||Method:{1}&quot;.
        /// </summary>
        internal static string RUNTIMEWRAPPER_ENTER {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_ENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Exited Automation RunTime Wrapper||Class:{0}||Method:{1}&quot;.
        /// </summary>
        internal static string RUNTIMEWRAPPER_EXIT {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Invalid {0} -&apos;{1}&apos; provided&quot;.
        /// </summary>
        internal static string RUNTIMEWRAPPER_INVALID_DATA {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Automation Runtime Wrapper Parameters Passed||ParamName:{0}||Direction:{1}||Value:{2}&quot;.
        /// </summary>
        internal static string RUNTIMEWRAPPER_PARAMETERS {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Text Area Failed.
        /// </summary>
        internal static string RUNTIMEWRAPPER_ReadTextAreaFailure {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_ReadTextAreaFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Automation Runtime Wrapper Variable||Name:{0}||Value:{1}&quot;.
        /// </summary>
        internal static string RUNTIMEWRAPPER_VARIABLE_VALUE {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_VARIABLE_VALUE", resourceCulture);
            }
        }
    }
}
