//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPAdapter.SoapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221", ConfigurationName="SoapService.UtilityProcessDispatcherv221PortType")]
    public interface UtilityProcessDispatcherv221PortType {
        
        // CODEGEN: Generating message contract since the operation Initialise is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BPAdapter.SoapService.InitialiseResponse1 Initialise(BPAdapter.SoapService.InitialiseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BPAdapter.SoapService.InitialiseResponse1> InitialiseAsync(BPAdapter.SoapService.InitialiseRequest request);
        
        // CODEGEN: Generating message contract since the operation CleanUp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BPAdapter.SoapService.CleanUpResponse1 CleanUp(BPAdapter.SoapService.CleanUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BPAdapter.SoapService.CleanUpResponse1> CleanUpAsync(BPAdapter.SoapService.CleanUpRequest request);
        
        // CODEGEN: Generating message contract since the operation RunProcess is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BPAdapter.SoapService.RunProcessResponse1 RunProcess(BPAdapter.SoapService.RunProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BPAdapter.SoapService.RunProcessResponse1> RunProcessAsync(BPAdapter.SoapService.RunProcessRequest request);
        
        // CODEGEN: Generating message contract since the operation GetProcessStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BPAdapter.SoapService.GetProcessStatusResponse1 GetProcessStatus(BPAdapter.SoapService.GetProcessStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BPAdapter.SoapService.GetProcessStatusResponse1> GetProcessStatusAsync(BPAdapter.SoapService.GetProcessStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221")]
    public partial class Initialise : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221")]
    public partial class InitialiseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bpInstanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bpInstance {
            get {
                return this.bpInstanceField;
            }
            set {
                this.bpInstanceField = value;
                this.RaisePropertyChanged("bpInstance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitialiseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221", Order=0)]
        public BPAdapter.SoapService.Initialise Initialise;
        
        public InitialiseRequest() {
        }
        
        public InitialiseRequest(BPAdapter.SoapService.Initialise Initialise) {
            this.Initialise = Initialise;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitialiseResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221", Order=0)]
        public BPAdapter.SoapService.InitialiseResponse InitialiseResponse;
        
        public InitialiseResponse1() {
        }
        
        public InitialiseResponse1(BPAdapter.SoapService.InitialiseResponse InitialiseResponse) {
            this.InitialiseResponse = InitialiseResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221")]
    public partial class CleanUp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bpInstanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bpInstance {
            get {
                return this.bpInstanceField;
            }
            set {
                this.bpInstanceField = value;
                this.RaisePropertyChanged("bpInstance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221")]
    public partial class CleanUpResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CleanUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221", Order=0)]
        public BPAdapter.SoapService.CleanUp CleanUp;
        
        public CleanUpRequest() {
        }
        
        public CleanUpRequest(BPAdapter.SoapService.CleanUp CleanUp) {
            this.CleanUp = CleanUp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CleanUpResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221", Order=0)]
        public BPAdapter.SoapService.CleanUpResponse CleanUpResponse;
        
        public CleanUpResponse1() {
        }
        
        public CleanUpResponse1(BPAdapter.SoapService.CleanUpResponse CleanUpResponse) {
            this.CleanUpResponse = CleanUpResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221")]
    public partial class RunProcess : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bpInstanceField;
        
        private string transactionIDField;
        
        private string processNameField;
        
        private string processParametersField;
        
        private string callbackInfoField;
        
        private bool useSSOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bpInstance {
            get {
                return this.bpInstanceField;
            }
            set {
                this.bpInstanceField = value;
                this.RaisePropertyChanged("bpInstance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProcessName {
            get {
                return this.processNameField;
            }
            set {
                this.processNameField = value;
                this.RaisePropertyChanged("ProcessName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProcessParameters {
            get {
                return this.processParametersField;
            }
            set {
                this.processParametersField = value;
                this.RaisePropertyChanged("ProcessParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CallbackInfo {
            get {
                return this.callbackInfoField;
            }
            set {
                this.callbackInfoField = value;
                this.RaisePropertyChanged("CallbackInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool UseSSO {
            get {
                return this.useSSOField;
            }
            set {
                this.useSSOField = value;
                this.RaisePropertyChanged("UseSSO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221")]
    public partial class RunProcessResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221", Order=0)]
        public BPAdapter.SoapService.RunProcess RunProcess;
        
        public RunProcessRequest() {
        }
        
        public RunProcessRequest(BPAdapter.SoapService.RunProcess RunProcess) {
            this.RunProcess = RunProcess;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunProcessResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221", Order=0)]
        public BPAdapter.SoapService.RunProcessResponse RunProcessResponse;
        
        public RunProcessResponse1() {
        }
        
        public RunProcessResponse1(BPAdapter.SoapService.RunProcessResponse RunProcessResponse) {
            this.RunProcessResponse = RunProcessResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221")]
    public partial class GetProcessStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bpInstanceField;
        
        private string transactionIDField;
        
        private bool useSSOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bpInstance {
            get {
                return this.bpInstanceField;
            }
            set {
                this.bpInstanceField = value;
                this.RaisePropertyChanged("bpInstance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool UseSSO {
            get {
                return this.useSSOField;
            }
            set {
                this.useSSOField = value;
                this.RaisePropertyChanged("UseSSO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221")]
    public partial class GetProcessStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221", Order=0)]
        public BPAdapter.SoapService.GetProcessStatus GetProcessStatus;
        
        public GetProcessStatusRequest() {
        }
        
        public GetProcessStatusRequest(BPAdapter.SoapService.GetProcessStatus GetProcessStatus) {
            this.GetProcessStatus = GetProcessStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:blueprism:webservice:utilityprocessdispatcherv221", Order=0)]
        public BPAdapter.SoapService.GetProcessStatusResponse GetProcessStatusResponse;
        
        public GetProcessStatusResponse1() {
        }
        
        public GetProcessStatusResponse1(BPAdapter.SoapService.GetProcessStatusResponse GetProcessStatusResponse) {
            this.GetProcessStatusResponse = GetProcessStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UtilityProcessDispatcherv221PortTypeChannel : BPAdapter.SoapService.UtilityProcessDispatcherv221PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilityProcessDispatcherv221PortTypeClient : System.ServiceModel.ClientBase<BPAdapter.SoapService.UtilityProcessDispatcherv221PortType>, BPAdapter.SoapService.UtilityProcessDispatcherv221PortType {
        
        public UtilityProcessDispatcherv221PortTypeClient() {
        }
        
        public UtilityProcessDispatcherv221PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilityProcessDispatcherv221PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityProcessDispatcherv221PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityProcessDispatcherv221PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPAdapter.SoapService.InitialiseResponse1 BPAdapter.SoapService.UtilityProcessDispatcherv221PortType.Initialise(BPAdapter.SoapService.InitialiseRequest request) {
            return base.Channel.Initialise(request);
        }
        
        public BPAdapter.SoapService.InitialiseResponse Initialise(BPAdapter.SoapService.Initialise Initialise1) {
            BPAdapter.SoapService.InitialiseRequest inValue = new BPAdapter.SoapService.InitialiseRequest();
            inValue.Initialise = Initialise1;
            BPAdapter.SoapService.InitialiseResponse1 retVal = ((BPAdapter.SoapService.UtilityProcessDispatcherv221PortType)(this)).Initialise(inValue);
            return retVal.InitialiseResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BPAdapter.SoapService.InitialiseResponse1> BPAdapter.SoapService.UtilityProcessDispatcherv221PortType.InitialiseAsync(BPAdapter.SoapService.InitialiseRequest request) {
            return base.Channel.InitialiseAsync(request);
        }
        
        public System.Threading.Tasks.Task<BPAdapter.SoapService.InitialiseResponse1> InitialiseAsync(BPAdapter.SoapService.Initialise Initialise) {
            BPAdapter.SoapService.InitialiseRequest inValue = new BPAdapter.SoapService.InitialiseRequest();
            inValue.Initialise = Initialise;
            return ((BPAdapter.SoapService.UtilityProcessDispatcherv221PortType)(this)).InitialiseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPAdapter.SoapService.CleanUpResponse1 BPAdapter.SoapService.UtilityProcessDispatcherv221PortType.CleanUp(BPAdapter.SoapService.CleanUpRequest request) {
            return base.Channel.CleanUp(request);
        }
        
        public BPAdapter.SoapService.CleanUpResponse CleanUp(BPAdapter.SoapService.CleanUp CleanUp1) {
            BPAdapter.SoapService.CleanUpRequest inValue = new BPAdapter.SoapService.CleanUpRequest();
            inValue.CleanUp = CleanUp1;
            BPAdapter.SoapService.CleanUpResponse1 retVal = ((BPAdapter.SoapService.UtilityProcessDispatcherv221PortType)(this)).CleanUp(inValue);
            return retVal.CleanUpResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BPAdapter.SoapService.CleanUpResponse1> BPAdapter.SoapService.UtilityProcessDispatcherv221PortType.CleanUpAsync(BPAdapter.SoapService.CleanUpRequest request) {
            return base.Channel.CleanUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<BPAdapter.SoapService.CleanUpResponse1> CleanUpAsync(BPAdapter.SoapService.CleanUp CleanUp) {
            BPAdapter.SoapService.CleanUpRequest inValue = new BPAdapter.SoapService.CleanUpRequest();
            inValue.CleanUp = CleanUp;
            return ((BPAdapter.SoapService.UtilityProcessDispatcherv221PortType)(this)).CleanUpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPAdapter.SoapService.RunProcessResponse1 BPAdapter.SoapService.UtilityProcessDispatcherv221PortType.RunProcess(BPAdapter.SoapService.RunProcessRequest request) {
            return base.Channel.RunProcess(request);
        }
        
        public BPAdapter.SoapService.RunProcessResponse RunProcess(BPAdapter.SoapService.RunProcess RunProcess1) {
            BPAdapter.SoapService.RunProcessRequest inValue = new BPAdapter.SoapService.RunProcessRequest();
            inValue.RunProcess = RunProcess1;
            BPAdapter.SoapService.RunProcessResponse1 retVal = ((BPAdapter.SoapService.UtilityProcessDispatcherv221PortType)(this)).RunProcess(inValue);
            return retVal.RunProcessResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BPAdapter.SoapService.RunProcessResponse1> BPAdapter.SoapService.UtilityProcessDispatcherv221PortType.RunProcessAsync(BPAdapter.SoapService.RunProcessRequest request) {
            return base.Channel.RunProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<BPAdapter.SoapService.RunProcessResponse1> RunProcessAsync(BPAdapter.SoapService.RunProcess RunProcess) {
            BPAdapter.SoapService.RunProcessRequest inValue = new BPAdapter.SoapService.RunProcessRequest();
            inValue.RunProcess = RunProcess;
            return ((BPAdapter.SoapService.UtilityProcessDispatcherv221PortType)(this)).RunProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPAdapter.SoapService.GetProcessStatusResponse1 BPAdapter.SoapService.UtilityProcessDispatcherv221PortType.GetProcessStatus(BPAdapter.SoapService.GetProcessStatusRequest request) {
            return base.Channel.GetProcessStatus(request);
        }
        
        public BPAdapter.SoapService.GetProcessStatusResponse GetProcessStatus(BPAdapter.SoapService.GetProcessStatus GetProcessStatus1) {
            BPAdapter.SoapService.GetProcessStatusRequest inValue = new BPAdapter.SoapService.GetProcessStatusRequest();
            inValue.GetProcessStatus = GetProcessStatus1;
            BPAdapter.SoapService.GetProcessStatusResponse1 retVal = ((BPAdapter.SoapService.UtilityProcessDispatcherv221PortType)(this)).GetProcessStatus(inValue);
            return retVal.GetProcessStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BPAdapter.SoapService.GetProcessStatusResponse1> BPAdapter.SoapService.UtilityProcessDispatcherv221PortType.GetProcessStatusAsync(BPAdapter.SoapService.GetProcessStatusRequest request) {
            return base.Channel.GetProcessStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<BPAdapter.SoapService.GetProcessStatusResponse1> GetProcessStatusAsync(BPAdapter.SoapService.GetProcessStatus GetProcessStatus) {
            BPAdapter.SoapService.GetProcessStatusRequest inValue = new BPAdapter.SoapService.GetProcessStatusRequest();
            inValue.GetProcessStatus = GetProcessStatus;
            return ((BPAdapter.SoapService.UtilityProcessDispatcherv221PortType)(this)).GetProcessStatusAsync(inValue);
        }
    }
}
