/****************************************************************
Copyright 2021 Infosys Ltd. 
Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at 
http://www.apache.org/licenses/
 ***************************************************************/
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace IMSWorkBench.Infrastructure.Interface.Constants
{
    /// <summary>
    /// Constants for event topic names.
    /// </summary>
    public class EventTopicNames
    {
        /// <summary>
        /// Event fired to tell the shell to update the status panel
        /// </summary>
        public const string StatusUpdate = "StatusUpdate";
        public const string Existing = "Existing";
        public const string ProcessSelected = "ProcessSelected";
        public const string Run = "Run";
        public const string Edit = "Edit";
        public const string FormClosing = "FormClosing";
        public const string Modify = "Modify";
        public const string Script = "Script";
        public const string Execute = "Execute";
        public const string Record = "Record";
        public const string StopRecording = "StopRecording";
        public const string Open = "Open";
        public const string Delete = "Delete";
        public const string ClickStream = "ClickStream";
        public const string AllData = "AllData";
        public const string Save = "Save";
        public const string RichText = "RichText";
        public const string ExecuteScript = "ExecuteScript";
        public const string ToggleDeckPanel = "ToggleDeckPanel";
        public const string SaveImageIntr = "SaveImageIntr";
        public const string Maximize = "Maximize";
        public const string Exit = "Exit";
        public const string LoadGeneric = "LoadGeneric";
        public const string SmartPartClosing = "SmartPartClosing";
        public const string OpenWFFromRepository = "OpenWFFromRepository";
        public const string Showtoolbar = "Showtoolbar";
        public const string CopyControl = "CopyControl";
        public const string SetCurrentTab = "SetCurrentTab";
        public const string CurrentTab = "CurrentTab";
        public const string UpdateSelectedNode = "UpdateSelectedNode";
        public const string TerminateApp = "TerminateApp";
        public const string TabHover = "TabHover";
        public const string TabHoverSet = "TabHoverSet";
        public const string NeWWorkflow = "NewWorkflow";
        public const string OpenWorkflow = "OpenWorkflow";
        public const string SaveWorkflow = "SaveWorkflow";
        public const string CloseWFTab = "CloseWFTab";
        public const string RunWF = "RunWF";
        public const string PublishWF = "PublishWF";
        public const string WFView = "WFView";
        public const string NewObjModel = "NewObjModel";
        public const string OpenAtr = "OpenAtr";
        public const string SaveAtr = "SaveAtr";
        public const string DeleteNode = "DeleteNode";
        public const string CloseObjModelTab = "CloseObjModelTab";
        public const string ShowDockPanel = "ShowDockPanel";
        public const string NewScript = "NewScript";
        public const string OpenScript = "OpenScript";
        public const string RunScripts = "RunScripts";
        public const string SaveScript = "SaveScript";
        public const string RunScripts_View = "RunScripts_View";
        public const string CloseTabScripts = "CloseTabScripts";
        public const string PublishScript = "PublishScript";
        public const string ScriptRepositoryView = "ScriptRepositoryView";
        public const string AdminView = "AdminView";
        public const string CloseAdminView = "CloseAdminView";
        public const string DeleteAdminNode = "DeleteAdminNode";
        public const string GroupExplorer = "GroupExplorer";
        public const string ActivateMenu = "ActivateMenu";
        public const string ShowUserLogged = "ShowUserLogged";
        public const string ShowOutputView = "ShowOutputView";
        public const string AppendOutputView = "AppendOutputView";
        public const string AppendOutputViewWF = "AppendOutputViewWF";
        public const string CloseOutputView = "CloseOutputView";
        public const string WFSave = "WFSave";
        public const string RefreshCategories = "RefreshCategories";
        public const string CategoryDeleted = "CategoryDeleted";
        public const string SaveAndClose = "SaveAndClose";
        public const string ScriptSave = "ScriptSave";
        public const string OMSave = "OMSave";
        public const string DeActivatePublish = "DeActivatePublish";
        public const string ActivatePublish = "ActivatePublish";
        public const string CollapseObjectExplorer = "CollapseObjectExplorer";
        public const string RefreshExplore = "RefreshExplore";
        public const string DisablePublish = "DisablePublish";
        public const string CurrentTabSelected = "CurrentTabSelected";
        public const string ShowRun = "ShowRun";
        public const string TransactionView = "TransactionView";
        public const string ShowTransaction = "ShowTransaction";
        public const string DeleteScript = "DeleteScript";
        public const string DeleteWF = "DeleteWF";
        public const string EnableDeleteMenu = "EnableDeleteMenu";
        public const string Replay = "Replay";
        public const string OpenScriptFromPackage = "OpenScriptFromPackage";
        public const string OpenWFFromPackage = "OpenWFFromPackage";
        public const string RecorderView = "RecorderView";
        public const string CloseRecorderView = "CloseRecorderView";
        public const string MinimizeShell = "MinimizeShell";
        public const string RecordingView = "RecordingView";
        public const string PublishPlaybackScript = "PublishPlaybackScript";
        public const string CloseRecordingTab = "CloseRecordingTab";
        public const string GeneratePlaybackScript = "GeneratePlaybackScript";
        public const string DisableGeneratePlaybackScript = "DisableGeneratePlaybackScript";
        public const string ExecutePlaybackScript = "ExecutePlaybackScript";
        public const string RunPlaybackScript = "RunPlaybackScript";
        public const string RunWFSelector = "RunWFSelector";
        public const string RunWFSelectorEvent = "RunWFSelectorEvent";
        public const string ExportScriptsView = "ExportScriptsView";
    }
}



