/****************************************************************
Copyright 2021 Infosys Ltd. 
Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at 
http://www.apache.org/licenses/
 ***************************************************************/
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The ActionCatalogException class is the exception used by the ActionCatalogService
// 
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;

namespace IMSWorkBench.Infrastructure.Library.Services
{
    [Serializable]
    public class ActionCatalogException : Exception
    {
        public ActionCatalogException()
            : base()
        {
        }

        public ActionCatalogException(string message)
            : base(message)
        {

        }

        public ActionCatalogException(string message, Exception innerException)
            : base(message, innerException)
        {

        }
    }
}
