/****************************************************************
Copyright 2021 Infosys Ltd. 
Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at 
http://www.apache.org/licenses/
 ***************************************************************/
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The IDependentModuleInfo interface is used along with the DependantModuleLoaderService.
// 
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.Practices.CompositeUI.Configuration;

namespace IMSWorkBench.Infrastructure.Library.Services
{
    public interface IDependentModuleInfo : IModuleInfo
    {
        IList<string> Dependencies { get; }
        string Name { get; }
    }
}
