/****************************************************************
Copyright 2021 Infosys Ltd. 
Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at 
http://www.apache.org/licenses/
 ***************************************************************/
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The SolutionProfileV1Parser class provides the implementation for v1 of the Profile Catalog
// 
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System.Collections.Generic;
using IMSWorkBench.Infrastructure.Library.SolutionProfileV1;
using Microsoft.Practices.CompositeUI.Configuration;
using IMSWorkBench.Infrastructure.Library.Services;

namespace IMSWorkBench.Infrastructure.Library.Services
{
    public class SolutionProfileV1Parser : ISolutionProfileParser
    {
        public const string Namespace = "http://schemas.microsoft.com/pag/cab-profile";

        public IModuleInfo[] Parse(string xml)
        {
            SolutionProfileElement solution = XmlValidationHelper.DeserializeXml<SolutionProfileV1.SolutionProfileElement>(xml,
                "SolutionProfileV1.xsd", Namespace);

            List<ModuleInfo> mis = new List<ModuleInfo>();

            if (solution.Modules != null)
            {
                foreach (ModuleInfoElement moduleInfo in solution.Modules)
                {
                    ModuleInfo mi = new ModuleInfo(moduleInfo.AssemblyFile);
                    SetModuleRoles(moduleInfo, mi);
                    mis.Add(mi);
                }
            }

            return mis.ToArray();
        }

        private static void SetModuleRoles(ModuleInfoElement moduleInfo, ModuleInfo mi)
        {
            if (moduleInfo.Roles != null && moduleInfo.Roles.Length > 0)
                foreach (RoleElement role in moduleInfo.Roles)
                    mi.AddRoles(role.Allow);
        }
    }
}

