//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Infrastructure.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infosys.WEM.Infrastructure.Common.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client cannot be empty!.
        /// </summary>
        public static string Client_Empty {
            get {
                return ResourceManager.GetString("Client_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No companies found in Companies table..
        /// </summary>
        public static string Companies_Not_Found {
            get {
                return ResourceManager.GetString("Companies_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name cannot be empty!.
        /// </summary>
        public static string Company_Name_Empty {
            get {
                return ResourceManager.GetString("Company_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It seems like we are facing some technical difficulties at the moment, sorry for the inconvenience caused. Please try visiting us later; we are trying to resolve your issue..
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was not formatted correctly..
        /// </summary>
        public static string Data_Format_Error {
            get {
                return ResourceManager.GetString("Data_Format_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of entity {0} for attribute(s) {1} was not found. For transaction with {2}.
        /// </summary>
        public static string Data_NotFound {
            get {
                return ResourceManager.GetString("Data_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device cannot be empty!.
        /// </summary>
        public static string Device_Empty {
            get {
                return ResourceManager.GetString("Device_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with {0} and {1} could not be uploaded. Error Message: {2}.
        /// </summary>
        public static string Document_Upload_Failed {
            get {
                return ResourceManager.GetString("Document_Upload_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script name is already present in this category.
        /// </summary>
        public static string Duplicate_Script_Name {
            get {
                return ResourceManager.GetString("Duplicate_Script_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow name is already present in this category.
        /// </summary>
        public static string Duplicate_Workflow_Name {
            get {
                return ResourceManager.GetString("Duplicate_Workflow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload Validation Failed. Reason: {0}.
        /// </summary>
        public static string FileUpload_Validation_Failed {
            get {
                return ResourceManager.GetString("FileUpload_Validation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value: {0} for property {1} is using reserved keyword(s) which is not permitted. Please modify the name using valid alphanumeric characters only and re-submit..
        /// </summary>
        public static string InvalidCharacter_Validation {
            get {
                return ResourceManager.GetString("InvalidCharacter_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send message to queue..
        /// </summary>
        public static string Message_Send_Failure {
            get {
                return ResourceManager.GetString("Message_Send_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter values passed to method is Invalid or Empty..
        /// </summary>
        public static string Method_Input_Parameters_Invalid {
            get {
                return ResourceManager.GetString("Method_Input_Parameters_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch presentation, as the keys provided do not match with any active records in our database..
        /// </summary>
        public static string PKandRK_Validation_Failed {
            get {
                return ResourceManager.GetString("PKandRK_Validation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request send to the worker for procesing conatins either invalid parameters or some mandatory fields do not contain the required data..
        /// </summary>
        public static string Request_Parameters_Invalid {
            get {
                return ResourceManager.GetString("Request_Parameters_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceIP cannot be null!.
        /// </summary>
        public static string Source_IP_Empty {
            get {
                return ResourceManager.GetString("Source_IP_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have faced a error we are unable to resolve at the moment. Please contact the administrator (Support ID: {handlingInstanceId})..
        /// </summary>
        public static string Standard_Error {
            get {
                return ResourceManager.GetString("Standard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be null!.
        /// </summary>
        public static string Title_Empty {
            get {
                return ResourceManager.GetString("Title_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} already present in this category.
        /// </summary>
        public static string User_Exists {
            get {
                return ResourceManager.GetString("User_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Validation Check Failed..
        /// </summary>
        public static string Validation_Errors {
            get {
                return ResourceManager.GetString("Validation_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow with PartitionKey {0} and RowKey {1} does not exist..
        /// </summary>
        public static string WorkflowEntity_Not_Found {
            get {
                return ResourceManager.GetString("WorkflowEntity_Not_Found", resourceCulture);
            }
        }
    }
}
