//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Infrastructure.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InformationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infosys.WEM.Infrastructure.Common.InformationMessages", typeof(InformationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Entered Automation RunTime Activity||ActivityInstanceId:{0}||Event:{1}||ControlType:{2}}&quot;.
        /// </summary>
        public static string ACTIVITY_AUTOMATIONRUNTIME_ENTER {
            get {
                return ResourceManager.GetString("ACTIVITY_AUTOMATIONRUNTIME_ENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Exit Automation RunTime Activity with Failure||ActivityInstanceId:{0}||ErrorMsg:{1}&quot;.
        /// </summary>
        public static string ACTIVITY_AUTOMATIONRUNTIME_EXIT_FAILURE {
            get {
                return ResourceManager.GetString("ACTIVITY_AUTOMATIONRUNTIME_EXIT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Exit Automation RunTime Activity with Success||ActivityInstanceId:{0}||&quot;.
        /// </summary>
        public static string ACTIVITY_AUTOMATIONRUNTIME_EXIT_SUCCESS {
            get {
                return ResourceManager.GetString("ACTIVITY_AUTOMATIONRUNTIME_EXIT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Automation Runtime Parameters Passed||ActivityInstanceId:{0}||ParamName:{1}||Direction:{2}||Value:{3}&quot;.
        /// </summary>
        public static string ACTIVITY_AUTOMATIONRUNTIME_PARAMETERS {
            get {
                return ResourceManager.GetString("ACTIVITY_AUTOMATIONRUNTIME_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Entered Activity||ActivityInstanceId:{0}||Activity:{1}&quot;.
        /// </summary>
        public static string ACTIVITY_ENTER {
            get {
                return ResourceManager.GetString("ACTIVITY_ENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Exit Activity with Failure||ActivityInstanceId:{0}||Activity:{2}||ErrorMsg:{1}&quot;.
        /// </summary>
        public static string ACTIVITY_EXIT_FAILURE {
            get {
                return ResourceManager.GetString("ACTIVITY_EXIT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Exit Activity with Success||ActivityInstanceId:{0}||Activity:{1}&quot;.
        /// </summary>
        public static string ACTIVITY_EXIT_SUCCESS {
            get {
                return ResourceManager.GetString("ACTIVITY_EXIT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Script Invoke Execution Start||ActivityInstanceId:{0}||ScriptName:{1}||ScriptId:{2}||ScriptSubCategoryId:{3}&quot;.
        /// </summary>
        public static string ACTIVITY_INVOKESCRIPT_BEGINSCRIPTINVOKE {
            get {
                return ResourceManager.GetString("ACTIVITY_INVOKESCRIPT_BEGINSCRIPTINVOKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Script Invoked Execution  End||ActivityInstanceId:{0}||ScriptName:{1}||ScriptId:{2}||ScriptSubCategoryId:{3}&quot;.
        /// </summary>
        public static string ACTIVITY_INVOKESCRIPT_ENDSCRIPTINVOKE {
            get {
                return ResourceManager.GetString("ACTIVITY_INVOKESCRIPT_ENDSCRIPTINVOKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Parameters Returned||ActivityInstanceId:{0}||ParamName:{1}||Value:{3}.
        /// </summary>
        public static string ACTIVITY_INVOKESCRIPT_PARAMETERS_OUT {
            get {
                return ResourceManager.GetString("ACTIVITY_INVOKESCRIPT_PARAMETERS_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Activity Parameters Passed||ActivityInstanceId:{0}||Activity:{4}||ParamName:{1}||Direction:{2}||Value:{3}&quot;.
        /// </summary>
        public static string ACTIVITY_PARAMETERS {
            get {
                return ResourceManager.GetString("ACTIVITY_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin invoke REST service.
        /// </summary>
        public static string ACTIVITY_RESTSERVICES_CALL_BEGIN {
            get {
                return ResourceManager.GetString("ACTIVITY_RESTSERVICES_CALL_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ACTIVITY_RESTSERVICES_CALL_END {
            get {
                return ResourceManager.GetString("ACTIVITY_RESTSERVICES_CALL_END", resourceCulture);
            }
        }
    }
}
