/****************************************************************
Copyright 2021 Infosys Ltd. 
Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at 
http://www.apache.org/licenses/
 ***************************************************************/
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The IActionCondition interface is used along with the IActionCatalogService
// to provide the conditional execution of an action. By implementing this interface you 
// will be able to register it in the ActionCatalogService.
//
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using Microsoft.Practices.CompositeUI;

namespace IMSWorkBench.Infrastructure.Interface.Services
{
    public interface IActionCondition
    {
        bool CanExecute(string action, WorkItem context, object caller, object target);
    }
}
