/****************************************************************
Copyright 2021 Infosys Ltd. 
Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at 
http://www.apache.org/licenses/
 ***************************************************************/
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The IImpersonationService interface defines the contract to implement impersonation.
// The Reference Implementation 2 has an implementation using GenericPrincipal
//
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using Microsoft.Practices.CompositeUI.Services;

namespace IMSWorkBench.Infrastructure.Interface.Services
{
    public interface IImpersonationService
    {
        IAuthenticationService AuthenticationService
        {
            get;
        }

        IImpersonationContext Impersonate();
    }
}
