//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace IMSWorkBench.Scripts.Constants
{
    /// <summary>
    /// Constants for UI extension site names.
    /// </summary>
    public class UIExtensionSiteNames : IMSWorkBench.Infrastructure.Interface.Constants.UIExtensionSiteNames
    {
    }
}
