//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace IMSWorkBench.Scripts.Constants
{
    /// <summary>
    /// Constants for workspace names.
    /// </summary>
    public class WorkspaceNames : IMSWorkBench.Infrastructure.Interface.Constants.WorkspaceNames
    {
        public const string AppWorkspace = "AppWorkspace";
        public const string ScriptsWorkspace = "ScriptsWorkspace";
    }
}
