//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptRepository.ScriptServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetScriptDetailsResMsg", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Mes" +
        "sage")]
    [System.SerializableAttribute()]
    public partial class GetScriptDetailsResMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScriptRepository.ScriptServiceRef.Script ScriptDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScriptRepository.ScriptServiceRef.Script ScriptDetails {
            get {
                return this.ScriptDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptDetailsField, value) != true)) {
                    this.ScriptDetailsField = value;
                    this.RaisePropertyChanged("ScriptDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Script", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Dat" +
        "a")]
    [System.SerializableAttribute()]
    public partial class Script : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArgStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BelongsToAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BelongsToOrgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BelongsToTrackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScriptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScriptTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScriptURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskCmdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkingDirField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArgString {
            get {
                return this.ArgStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ArgStringField, value) != true)) {
                    this.ArgStringField = value;
                    this.RaisePropertyChanged("ArgString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BelongsToAccount {
            get {
                return this.BelongsToAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BelongsToAccountField, value) != true)) {
                    this.BelongsToAccountField = value;
                    this.RaisePropertyChanged("BelongsToAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BelongsToOrg {
            get {
                return this.BelongsToOrgField;
            }
            set {
                if ((object.ReferenceEquals(this.BelongsToOrgField, value) != true)) {
                    this.BelongsToOrgField = value;
                    this.RaisePropertyChanged("BelongsToOrg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BelongsToTrack {
            get {
                return this.BelongsToTrackField;
            }
            set {
                if ((object.ReferenceEquals(this.BelongsToTrackField, value) != true)) {
                    this.BelongsToTrackField = value;
                    this.RaisePropertyChanged("BelongsToTrack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScriptId {
            get {
                return this.ScriptIdField;
            }
            set {
                if ((this.ScriptIdField.Equals(value) != true)) {
                    this.ScriptIdField = value;
                    this.RaisePropertyChanged("ScriptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScriptType {
            get {
                return this.ScriptTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptTypeField, value) != true)) {
                    this.ScriptTypeField = value;
                    this.RaisePropertyChanged("ScriptType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScriptURL {
            get {
                return this.ScriptURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptURLField, value) != true)) {
                    this.ScriptURLField = value;
                    this.RaisePropertyChanged("ScriptURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubCategoryId {
            get {
                return this.SubCategoryIdField;
            }
            set {
                if ((this.SubCategoryIdField.Equals(value) != true)) {
                    this.SubCategoryIdField = value;
                    this.RaisePropertyChanged("SubCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskCmd {
            get {
                return this.TaskCmdField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskCmdField, value) != true)) {
                    this.TaskCmdField = value;
                    this.RaisePropertyChanged("TaskCmd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskType {
            get {
                return this.TaskTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskTypeField, value) != true)) {
                    this.TaskTypeField = value;
                    this.RaisePropertyChanged("TaskType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkingDir {
            get {
                return this.WorkingDirField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkingDirField, value) != true)) {
                    this.WorkingDirField = value;
                    this.RaisePropertyChanged("WorkingDir");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultError", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Infrastructure.Common")]
    [System.SerializableAttribute()]
    public partial class ServiceFaultError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllScriptDetailsResMsg", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Mes" +
        "sage")]
    [System.SerializableAttribute()]
    public partial class GetAllScriptDetailsResMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScriptRepository.ScriptServiceRef.Script[] ScriptsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScriptRepository.ScriptServiceRef.Script[] Scripts {
            get {
                return this.ScriptsField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptsField, value) != true)) {
                    this.ScriptsField = value;
                    this.RaisePropertyChanged("Scripts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllCategoryAndSubcategoryResMsg", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Mes" +
        "sage")]
    [System.SerializableAttribute()]
    public partial class GetAllCategoryAndSubcategoryResMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScriptRepository.ScriptServiceRef.Category[] CategoriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScriptRepository.ScriptServiceRef.Category[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Dat" +
        "a")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentCategoryIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentCategoryId {
            get {
                return this.ParentCategoryIdField;
            }
            set {
                if ((this.ParentCategoryIdField.Equals(value) != true)) {
                    this.ParentCategoryIdField = value;
                    this.RaisePropertyChanged("ParentCategoryId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCategoryOrSubcategoryReqMsg", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Mes" +
        "sage")]
    [System.SerializableAttribute()]
    public partial class AddCategoryOrSubcategoryReqMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScriptRepository.ScriptServiceRef.Category[] CategoriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScriptRepository.ScriptServiceRef.Category[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCategoryOrSubcategoryResMsg", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Mes" +
        "sage")]
    [System.SerializableAttribute()]
    public partial class AddCategoryOrSubcategoryResMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCategoryOrSubcategoryReqMsg", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Mes" +
        "sage")]
    [System.SerializableAttribute()]
    public partial class UpdateCategoryOrSubcategoryReqMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScriptRepository.ScriptServiceRef.Category[] CategoriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScriptRepository.ScriptServiceRef.Category[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCategoryOrSubcategoryResMsg", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Mes" +
        "sage")]
    [System.SerializableAttribute()]
    public partial class UpdateCategoryOrSubcategoryResMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteCategoryOrSubcategoryReqMsg", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Mes" +
        "sage")]
    [System.SerializableAttribute()]
    public partial class DeleteCategoryOrSubcategoryReqMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScriptRepository.ScriptServiceRef.Category[] CategoriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScriptRepository.ScriptServiceRef.Category[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteCategoryOrSubcategoryResMsg", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Scripts.Service.Contracts.Mes" +
        "sage")]
    [System.SerializableAttribute()]
    public partial class DeleteCategoryOrSubcategoryResMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScriptServiceRef.IScriptRepository")]
    public interface IScriptRepository {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScriptRepository/GetScriptDetails", ReplyAction="http://tempuri.org/IScriptRepository/GetScriptDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ScriptRepository.ScriptServiceRef.ServiceFaultError), Action="http://tempuri.org/IScriptRepository/GetScriptDetailsServiceFaultErrorFault", Name="ServiceFaultError", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Infrastructure.Common")]
        ScriptRepository.ScriptServiceRef.GetScriptDetailsResMsg GetScriptDetails(string scriptId, string subCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScriptRepository/GetAllScriptDetails", ReplyAction="http://tempuri.org/IScriptRepository/GetAllScriptDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ScriptRepository.ScriptServiceRef.ServiceFaultError), Action="http://tempuri.org/IScriptRepository/GetAllScriptDetailsServiceFaultErrorFault", Name="ServiceFaultError", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Infrastructure.Common")]
        ScriptRepository.ScriptServiceRef.GetAllScriptDetailsResMsg GetAllScriptDetails(string subCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScriptRepository/GetAllCategoryAndSubcategory", ReplyAction="http://tempuri.org/IScriptRepository/GetAllCategoryAndSubcategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ScriptRepository.ScriptServiceRef.ServiceFaultError), Action="http://tempuri.org/IScriptRepository/GetAllCategoryAndSubcategoryServiceFaultErro" +
            "rFault", Name="ServiceFaultError", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Infrastructure.Common")]
        ScriptRepository.ScriptServiceRef.GetAllCategoryAndSubcategoryResMsg GetAllCategoryAndSubcategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScriptRepository/AddCategoryOrSubcategory", ReplyAction="http://tempuri.org/IScriptRepository/AddCategoryOrSubcategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ScriptRepository.ScriptServiceRef.ServiceFaultError), Action="http://tempuri.org/IScriptRepository/AddCategoryOrSubcategoryServiceFaultErrorFau" +
            "lt", Name="ServiceFaultError", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Infrastructure.Common")]
        ScriptRepository.ScriptServiceRef.AddCategoryOrSubcategoryResMsg AddCategoryOrSubcategory(ScriptRepository.ScriptServiceRef.AddCategoryOrSubcategoryReqMsg value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScriptRepository/UpdateCategoryOrSubcategory", ReplyAction="http://tempuri.org/IScriptRepository/UpdateCategoryOrSubcategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ScriptRepository.ScriptServiceRef.ServiceFaultError), Action="http://tempuri.org/IScriptRepository/UpdateCategoryOrSubcategoryServiceFaultError" +
            "Fault", Name="ServiceFaultError", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Infrastructure.Common")]
        ScriptRepository.ScriptServiceRef.UpdateCategoryOrSubcategoryResMsg UpdateCategoryOrSubcategory(ScriptRepository.ScriptServiceRef.UpdateCategoryOrSubcategoryReqMsg value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScriptRepository/DeleteCategoryOrSubcategory", ReplyAction="http://tempuri.org/IScriptRepository/DeleteCategoryOrSubcategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ScriptRepository.ScriptServiceRef.ServiceFaultError), Action="http://tempuri.org/IScriptRepository/DeleteCategoryOrSubcategoryServiceFaultError" +
            "Fault", Name="ServiceFaultError", Namespace="http://schemas.datacontract.org/2004/07/Infosys.WEM.Infrastructure.Common")]
        ScriptRepository.ScriptServiceRef.DeleteCategoryOrSubcategoryResMsg DeleteCategoryOrSubcategory(ScriptRepository.ScriptServiceRef.DeleteCategoryOrSubcategoryReqMsg value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScriptRepositoryChannel : ScriptRepository.ScriptServiceRef.IScriptRepository, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScriptRepositoryClient : System.ServiceModel.ClientBase<ScriptRepository.ScriptServiceRef.IScriptRepository>, ScriptRepository.ScriptServiceRef.IScriptRepository {
        
        public ScriptRepositoryClient() {
        }
        
        public ScriptRepositoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScriptRepositoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScriptRepositoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScriptRepositoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ScriptRepository.ScriptServiceRef.GetScriptDetailsResMsg GetScriptDetails(string scriptId, string subCategoryId) {
            return base.Channel.GetScriptDetails(scriptId, subCategoryId);
        }
        
        public ScriptRepository.ScriptServiceRef.GetAllScriptDetailsResMsg GetAllScriptDetails(string subCategoryId) {
            return base.Channel.GetAllScriptDetails(subCategoryId);
        }
        
        public ScriptRepository.ScriptServiceRef.GetAllCategoryAndSubcategoryResMsg GetAllCategoryAndSubcategory() {
            return base.Channel.GetAllCategoryAndSubcategory();
        }
        
        public ScriptRepository.ScriptServiceRef.AddCategoryOrSubcategoryResMsg AddCategoryOrSubcategory(ScriptRepository.ScriptServiceRef.AddCategoryOrSubcategoryReqMsg value) {
            return base.Channel.AddCategoryOrSubcategory(value);
        }
        
        public ScriptRepository.ScriptServiceRef.UpdateCategoryOrSubcategoryResMsg UpdateCategoryOrSubcategory(ScriptRepository.ScriptServiceRef.UpdateCategoryOrSubcategoryReqMsg value) {
            return base.Channel.UpdateCategoryOrSubcategory(value);
        }
        
        public ScriptRepository.ScriptServiceRef.DeleteCategoryOrSubcategoryResMsg DeleteCategoryOrSubcategory(ScriptRepository.ScriptServiceRef.DeleteCategoryOrSubcategoryReqMsg value) {
            return base.Channel.DeleteCategoryOrSubcategory(value);
        }
    }
}
