//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The FormShell class represent the main form of your application.
// 
// The default Form supplied in this guidance package provides basic UI elements 
// like:
//      - A MenuStrip
//      - A ToolStrip
//      - A StatusStrip
//      - 2 WorkSpaces (left and right) separated by a spliter
//
// There is also a subscription to the "StatusUpdate" event topic used to change the
// content of the StatusStrip
//
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace IMSWorkBench.Infrastructure.Shell
{
    partial class ShellForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;
       

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ShellForm));
            this._mainStatusStrip = new System.Windows.Forms.StatusStrip();
            this.lblMode = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
            this._statusLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this.lblTransaction = new System.Windows.Forms.ToolStripStatusLabel();
            this._mainToolBar = new System.Windows.Forms.MenuStrip();
            this._fileMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._mainToolStrip = new System.Windows.Forms.ToolStrip();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.panel2 = new System.Windows.Forms.Panel();
            this.splitContainer2 = new System.Windows.Forms.SplitContainer();
            this._deckWorkspace = new Microsoft.Practices.CompositeUI.WPF.DeckWorkspace();
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
            this.toolStripButton2 = new System.Windows.Forms.ToolStripButton();
            this.pnlAutomation = new System.Windows.Forms.Panel();
            this.panel5 = new System.Windows.Forms.Panel();
            this.linkParent = new System.Windows.Forms.LinkLabel();
            this.txtAutomation = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this._automationWorkspace = new Microsoft.Practices.CompositeUI.WPF.DeckWorkspace();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel4 = new System.Windows.Forms.Panel();
            this.panel6 = new System.Windows.Forms.Panel();
            this.splitContainer3 = new System.Windows.Forms.SplitContainer();
            this._tabWorkspace = new Microsoft.Practices.CompositeUI.WinForms.TabWorkspace();
            this.pnlOutputView = new System.Windows.Forms.Panel();
            this.pnlDock = new System.Windows.Forms.Panel();
            this._utilWorkspace = new Microsoft.Practices.CompositeUI.WPF.DeckWorkspace();
            this.panel3 = new System.Windows.Forms.Panel();
            this.btnExpand = new System.Windows.Forms.Button();
            this.btnCollapse = new System.Windows.Forms.Button();
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            this._mainStatusStrip.SuspendLayout();
            this._mainToolBar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).BeginInit();
            this.splitContainer2.Panel1.SuspendLayout();
            this.splitContainer2.Panel2.SuspendLayout();
            this.splitContainer2.SuspendLayout();
            this.toolStrip1.SuspendLayout();
            this.pnlAutomation.SuspendLayout();
            this.panel5.SuspendLayout();
            this.panel1.SuspendLayout();
            this.panel4.SuspendLayout();
            this.panel6.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer3)).BeginInit();
            this.splitContainer3.Panel1.SuspendLayout();
            this.splitContainer3.Panel2.SuspendLayout();
            this.splitContainer3.SuspendLayout();
            this.pnlDock.SuspendLayout();
            this.panel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // _mainStatusStrip
            // 
            this._mainStatusStrip.BackColor = System.Drawing.SystemColors.ControlLight;
            this._mainStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.lblMode,
            this.toolStripStatusLabel1,
            this._statusLabel,
            this.lblTransaction});
            this._mainStatusStrip.Location = new System.Drawing.Point(0, 521);
            this._mainStatusStrip.Name = "_mainStatusStrip";
            this._mainStatusStrip.Size = new System.Drawing.Size(983, 22);
            this._mainStatusStrip.TabIndex = 2;
            this._mainStatusStrip.Text = "statusStrip1";
            // 
            // lblMode
            // 
            this.lblMode.Name = "lblMode";
            this.lblMode.Size = new System.Drawing.Size(0, 17);
            // 
            // toolStripStatusLabel1
            // 
            this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            this.toolStripStatusLabel1.Size = new System.Drawing.Size(0, 17);
            this.toolStripStatusLabel1.TextImageRelation = System.Windows.Forms.TextImageRelation.TextBeforeImage;
            this.toolStripStatusLabel1.Click += new System.EventHandler(this.toolStripStatusLabel1_Click);
            // 
            // _statusLabel
            // 
            this._statusLabel.Name = "_statusLabel";
            this._statusLabel.Size = new System.Drawing.Size(39, 17);
            this._statusLabel.Text = "Ready";
            // 
            // lblTransaction
            // 
            this.lblTransaction.Name = "lblTransaction";
            this.lblTransaction.Size = new System.Drawing.Size(0, 17);
            // 
            // _mainToolBar
            // 
            this._mainToolBar.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._fileMenu});
            this._mainToolBar.Location = new System.Drawing.Point(0, 0);
            this._mainToolBar.Name = "_mainToolBar";
            this._mainToolBar.Size = new System.Drawing.Size(983, 24);
            this._mainToolBar.TabIndex = 5;
            this._mainToolBar.Text = "menuStrip1";
            // 
            // _fileMenu
            // 
            this._fileMenu.Name = "_fileMenu";
            this._fileMenu.Size = new System.Drawing.Size(37, 20);
            this._fileMenu.Text = "File";
            // 
            // _mainToolStrip
            // 
            this._mainToolStrip.Location = new System.Drawing.Point(0, 24);
            this._mainToolStrip.Name = "_mainToolStrip";
            this._mainToolStrip.Size = new System.Drawing.Size(983, 25);
            this._mainToolStrip.TabIndex = 4;
            this._mainToolStrip.Text = "toolStrip1";
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 49);
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.panel2);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.panel1);
            this.splitContainer1.Size = new System.Drawing.Size(983, 472);
            this.splitContainer1.SplitterDistance = 228;
            this.splitContainer1.TabIndex = 6;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.White;
            this.panel2.Controls.Add(this.splitContainer2);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(228, 472);
            this.panel2.TabIndex = 0;
            // 
            // splitContainer2
            // 
            this.splitContainer2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer2.Location = new System.Drawing.Point(0, 0);
            this.splitContainer2.Name = "splitContainer2";
            this.splitContainer2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer2.Panel1
            // 
            this.splitContainer2.Panel1.Controls.Add(this._deckWorkspace);
            this.splitContainer2.Panel1.Controls.Add(this.toolStrip1);
            // 
            // splitContainer2.Panel2
            // 
            this.splitContainer2.Panel2.Controls.Add(this.pnlAutomation);
            this.splitContainer2.Panel2.Controls.Add(this._automationWorkspace);
            this.splitContainer2.Size = new System.Drawing.Size(228, 472);
            this.splitContainer2.SplitterDistance = 322;
            this.splitContainer2.TabIndex = 0;
            // 
            // _deckWorkspace
            // 
            this._deckWorkspace.BackColor = System.Drawing.Color.White;
            this._deckWorkspace.Dock = System.Windows.Forms.DockStyle.Fill;
            this._deckWorkspace.Location = new System.Drawing.Point(0, 25);
            this._deckWorkspace.Name = "_deckWorkspace";
            this._deckWorkspace.Size = new System.Drawing.Size(228, 297);
            this._deckWorkspace.TabIndex = 4;
            this._deckWorkspace.Text = "deckWorkspace1";
            // 
            // toolStrip1
            // 
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripButton1,
            this.toolStripButton2});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(228, 25);
            this.toolStrip1.TabIndex = 0;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // toolStripButton1
            // 
            this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButton1.Image")));
            this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButton1.Name = "toolStripButton1";
            this.toolStripButton1.Size = new System.Drawing.Size(23, 22);
            this.toolStripButton1.ToolTipText = "Start capturing the control details. Press \'SHIFT + move Mouse\' on the control";
            this.toolStripButton1.Click += new System.EventHandler(this.toolStripButton1_Click);
            // 
            // toolStripButton2
            // 
            this.toolStripButton2.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButton2.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButton2.Image")));
            this.toolStripButton2.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButton2.Name = "toolStripButton2";
            this.toolStripButton2.Size = new System.Drawing.Size(23, 22);
            this.toolStripButton2.ToolTipText = "Refresh ";
            this.toolStripButton2.Click += new System.EventHandler(this.toolStripButton2_Click);
            // 
            // pnlAutomation
            // 
            this.pnlAutomation.Controls.Add(this.panel5);
            this.pnlAutomation.Controls.Add(this.txtAutomation);
            this.pnlAutomation.Controls.Add(this.label1);
            this.pnlAutomation.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlAutomation.Location = new System.Drawing.Point(0, 0);
            this.pnlAutomation.Name = "pnlAutomation";
            this.pnlAutomation.Size = new System.Drawing.Size(228, 146);
            this.pnlAutomation.TabIndex = 1;
            // 
            // panel5
            // 
            this.panel5.Controls.Add(this.linkParent);
            this.panel5.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel5.Location = new System.Drawing.Point(0, 120);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(228, 26);
            this.panel5.TabIndex = 2;
            // 
            // linkParent
            // 
            this.linkParent.AutoSize = true;
            this.linkParent.Location = new System.Drawing.Point(2, 5);
            this.linkParent.Name = "linkParent";
            this.linkParent.Size = new System.Drawing.Size(124, 13);
            this.linkParent.TabIndex = 3;
            this.linkParent.TabStop = true;
            this.linkParent.Text = "Parent Control Properties";
            this.linkParent.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.linkParent_LinkClicked);
            // 
            // txtAutomation
            // 
            this.txtAutomation.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtAutomation.Location = new System.Drawing.Point(0, 13);
            this.txtAutomation.Margin = new System.Windows.Forms.Padding(10);
            this.txtAutomation.Multiline = true;
            this.txtAutomation.Name = "txtAutomation";
            this.txtAutomation.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.txtAutomation.Size = new System.Drawing.Size(228, 133);
            this.txtAutomation.TabIndex = 1;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Dock = System.Windows.Forms.DockStyle.Top;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(0, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(135, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Automation Properties:";
            // 
            // _automationWorkspace
            // 
            this._automationWorkspace.Dock = System.Windows.Forms.DockStyle.Fill;
            this._automationWorkspace.Location = new System.Drawing.Point(0, 0);
            this._automationWorkspace.Name = "_automationWorkspace";
            this._automationWorkspace.Size = new System.Drawing.Size(228, 146);
            this._automationWorkspace.TabIndex = 0;
            this._automationWorkspace.Text = "deckWorkspace1";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.panel4);
            this.panel1.Controls.Add(this.pnlDock);
            this.panel1.Controls.Add(this.panel3);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(751, 472);
            this.panel1.TabIndex = 0;
            // 
            // panel4
            // 
            this.panel4.Controls.Add(this.panel6);
            this.panel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel4.Location = new System.Drawing.Point(28, 0);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(379, 472);
            this.panel4.TabIndex = 3;
            // 
            // panel6
            // 
            this.panel6.Controls.Add(this.splitContainer3);
            this.panel6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel6.Location = new System.Drawing.Point(0, 0);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(379, 472);
            this.panel6.TabIndex = 2;
            // 
            // splitContainer3
            // 
            this.splitContainer3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer3.Location = new System.Drawing.Point(0, 0);
            this.splitContainer3.Name = "splitContainer3";
            this.splitContainer3.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer3.Panel1
            // 
            this.splitContainer3.Panel1.Controls.Add(this._tabWorkspace);
            // 
            // splitContainer3.Panel2
            // 
            this.splitContainer3.Panel2.Controls.Add(this.pnlOutputView);
            this.splitContainer3.Panel2Collapsed = true;
            this.splitContainer3.Size = new System.Drawing.Size(379, 472);
            this.splitContainer3.SplitterDistance = 290;
            this.splitContainer3.TabIndex = 0;
            // 
            // _tabWorkspace
            // 
            this._tabWorkspace.Dock = System.Windows.Forms.DockStyle.Fill;
            this._tabWorkspace.Location = new System.Drawing.Point(0, 0);
            this._tabWorkspace.Name = "_tabWorkspace";
            this._tabWorkspace.SelectedIndex = 0;
            this._tabWorkspace.ShowToolTips = true;
            this._tabWorkspace.Size = new System.Drawing.Size(379, 472);
            this._tabWorkspace.TabIndex = 3;
            this._tabWorkspace.SelectedIndexChanged += new System.EventHandler(this._tabWorkspace_SelectedIndexChanged);
            this._tabWorkspace.MouseHover += new System.EventHandler(this._tabWorkspace_MouseHover);
            // 
            // pnlOutputView
            // 
            this.pnlOutputView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlOutputView.Location = new System.Drawing.Point(0, 0);
            this.pnlOutputView.Name = "pnlOutputView";
            this.pnlOutputView.Size = new System.Drawing.Size(150, 46);
            this.pnlOutputView.TabIndex = 3;
            // 
            // pnlDock
            // 
            this.pnlDock.Controls.Add(this._utilWorkspace);
            this.pnlDock.Dock = System.Windows.Forms.DockStyle.Right;
            this.pnlDock.Location = new System.Drawing.Point(407, 0);
            this.pnlDock.Name = "pnlDock";
            this.pnlDock.Size = new System.Drawing.Size(344, 472);
            this.pnlDock.TabIndex = 2;
            // 
            // _utilWorkspace
            // 
            this._utilWorkspace.Dock = System.Windows.Forms.DockStyle.Fill;
            this._utilWorkspace.Location = new System.Drawing.Point(0, 0);
            this._utilWorkspace.Name = "_utilWorkspace";
            this._utilWorkspace.Size = new System.Drawing.Size(344, 472);
            this._utilWorkspace.TabIndex = 0;
            this._utilWorkspace.Text = "deckWorkspace1";
            // 
            // panel3
            // 
            this.panel3.BackColor = System.Drawing.Color.White;
            this.panel3.Controls.Add(this.btnExpand);
            this.panel3.Controls.Add(this.btnCollapse);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel3.Location = new System.Drawing.Point(0, 0);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(28, 472);
            this.panel3.TabIndex = 0;
            // 
            // btnExpand
            // 
            this.btnExpand.BackColor = System.Drawing.Color.White;
            this.btnExpand.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExpand.BackgroundImage")));
            this.btnExpand.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.btnExpand.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnExpand.FlatAppearance.BorderColor = System.Drawing.Color.White;
            this.btnExpand.FlatAppearance.BorderSize = 0;
            this.btnExpand.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExpand.Location = new System.Drawing.Point(0, 24);
            this.btnExpand.Name = "btnExpand";
            this.btnExpand.Size = new System.Drawing.Size(28, 448);
            this.btnExpand.TabIndex = 1;
            this.btnExpand.UseVisualStyleBackColor = false;
            this.btnExpand.Click += new System.EventHandler(this.btnExpand_Click);
            // 
            // btnCollapse
            // 
            this.btnCollapse.BackColor = System.Drawing.Color.White;
            this.btnCollapse.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCollapse.BackgroundImage")));
            this.btnCollapse.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.btnCollapse.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCollapse.FlatAppearance.BorderSize = 0;
            this.btnCollapse.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCollapse.Location = new System.Drawing.Point(0, 0);
            this.btnCollapse.Name = "btnCollapse";
            this.btnCollapse.Size = new System.Drawing.Size(28, 24);
            this.btnCollapse.TabIndex = 0;
            this.btnCollapse.UseVisualStyleBackColor = false;
            this.btnCollapse.Click += new System.EventHandler(this.btnCollapse_Click);
            // 
            // imageList1
            // 
            this.imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList1.Images.SetKeyName(0, "hover");
            this.imageList1.Images.SetKeyName(1, "normal");
            // 
            // ShellForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(983, 543);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this._mainToolStrip);
            this.Controls.Add(this._mainStatusStrip);
            this.Controls.Add(this._mainToolBar);
            this.MainMenuStrip = this._mainToolBar;
            this.Name = "ShellForm";
            this.Text = "Script Control Center - Automation Workbench";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.ShellForm_FormClosing);
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.ShellForm_FormClosed);
            this._mainStatusStrip.ResumeLayout(false);
            this._mainStatusStrip.PerformLayout();
            this._mainToolBar.ResumeLayout(false);
            this._mainToolBar.PerformLayout();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.splitContainer2.Panel1.ResumeLayout(false);
            this.splitContainer2.Panel1.PerformLayout();
            this.splitContainer2.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).EndInit();
            this.splitContainer2.ResumeLayout(false);
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.pnlAutomation.ResumeLayout(false);
            this.pnlAutomation.PerformLayout();
            this.panel5.ResumeLayout(false);
            this.panel5.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel4.ResumeLayout(false);
            this.panel6.ResumeLayout(false);
            this.splitContainer3.Panel1.ResumeLayout(false);
            this.splitContainer3.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer3)).EndInit();
            this.splitContainer3.ResumeLayout(false);
            this.pnlDock.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.StatusStrip _mainStatusStrip;
        private System.Windows.Forms.MenuStrip _mainToolBar;
        private System.Windows.Forms.ToolStripMenuItem _fileMenu;
        private System.Windows.Forms.ToolStrip _mainToolStrip;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.Button btnExpand;
        private System.Windows.Forms.Button btnCollapse;
        private System.Windows.Forms.Panel panel4;
        private System.Windows.Forms.Panel pnlDock;
        private Microsoft.Practices.CompositeUI.WPF.DeckWorkspace _utilWorkspace;
        private System.Windows.Forms.SplitContainer splitContainer2;
        private Microsoft.Practices.CompositeUI.WPF.DeckWorkspace _automationWorkspace;
        private Microsoft.Practices.CompositeUI.WPF.DeckWorkspace _deckWorkspace;
        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripButton toolStripButton1;
        private System.Windows.Forms.ToolStripButton toolStripButton2;
        private System.Windows.Forms.ImageList imageList1;
        private System.Windows.Forms.Panel pnlAutomation;
        private System.Windows.Forms.TextBox txtAutomation;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Panel panel5;
        private System.Windows.Forms.LinkLabel linkParent;
        private System.Windows.Forms.ToolStripStatusLabel lblMode;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        private System.Windows.Forms.ToolStripStatusLabel _statusLabel;
        private System.Windows.Forms.Panel panel6;
        private System.Windows.Forms.SplitContainer splitContainer3;
        private Microsoft.Practices.CompositeUI.WinForms.TabWorkspace _tabWorkspace;
        private System.Windows.Forms.Panel pnlOutputView;
        private System.Windows.Forms.ToolStripStatusLabel lblTransaction;

    }
}

