//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportConfigurationMaster
    {
        public int id { get; set; }
        public int TargetServerId { get; set; }
        public string TargetSystemUserId { get; set; }
        public string TargetSystemPassword { get; set; }
        public int ExportStatus { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ScriptRepositoryBaseServerAddress { get; set; }
    }
}
