//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportSourceTargetMapping
    {
        public int id { get; set; }
        public string SourceInstanceAddr { get; set; }
        public int SourceScriptCategoryId { get; set; }
        public int SourceScriptId { get; set; }
        public int SourceScriptVersion { get; set; }
        public int TargetInstanceId { get; set; }
        public int TargetScriptCategoryId { get; set; }
        public int TargetScriptId { get; set; }
        public int TargetScriptVersion { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
