//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportJobProcessingHistory
    {
        public int JobId { get; set; }
        public int ExportConfigurationId { get; set; }
        public System.DateTime StartedOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string ProcessingSystemIp { get; set; }
        public string ProcessingSystemName { get; set; }
        public string ProcessedBy { get; set; }
    }
}
