//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterredNodes
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public System.DateTime Timestamp { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> HttpPort { get; set; }
        public Nullable<int> TcpPort { get; set; }
        public System.DateTime RegisteredOn { get; set; }
        public Nullable<System.DateTime> UnRegisteredOn { get; set; }
        public string MachineName { get; set; }
        public string DomainName { get; set; }
        public string State { get; set; }
        public string OSVersion { get; set; }
        public bool Is64Bit { get; set; }
        public string WorkflowServiceVersion { get; set; }
        public string DotNetVersion { get; set; }
        public int ExecutionEngineSupported { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
