//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptExecuteRequest
    {
        public string PartitionKey { get; set; }
        public int scriptexecuterequestid { get; set; }
        public Nullable<System.Guid> transactionId { get; set; }
        public Nullable<int> scriptid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string scriptname { get; set; }
        public string inparams { get; set; }
        public string username { get; set; }
        public string remoteservernames { get; set; }
        public string remoteexecutionhost { get; set; }
        public Nullable<int> executionmodetype { get; set; }
        public string scheduledpattern { get; set; }
        public Nullable<System.DateTime> schedulestartdatetime { get; set; }
        public Nullable<System.DateTime> scheduleenddatetime { get; set; }
        public Nullable<int> scheduleoccurences { get; set; }
        public Nullable<int> schedulepriority { get; set; }
        public string scheduleonclusters { get; set; }
        public string iapnodetransport { get; set; }
        public string domain { get; set; }
        public string referencekey { get; set; }
        public string path { get; set; }
        public string ResponseNotificationCallbackURL { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    }
}
