//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int ScriptId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ScriptType { get; set; }
        public string TaskType { get; set; }
        public string TaskCmd { get; set; }
        public string ScriptURL { get; set; }
        public string ArgString { get; set; }
        public string WorkingDir { get; set; }
        public string BelongsToOrg { get; set; }
        public string BelongsToAccount { get; set; }
        public string BelongsToTrack { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int Version { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> RunAsAdmin { get; set; }
        public int CategoryId { get; set; }
        public Nullable<bool> UsesUIAutomation { get; set; }
        public string IfeaScriptName { get; set; }
        public string CallMethod { get; set; }
        public string Tags { get; set; }
        public string LicenseType { get; set; }
        public string SourceUrl { get; set; }
        public string ExternalReferences { get; set; }
    }
}
