//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptExecuteResponse
    {
        public string PartitionKey { get; set; }
        public int scriptexecuteresponseid { get; set; }
        public Nullable<System.Guid> transactionId { get; set; }
        public string currentstate { get; set; }
        public string successmessage { get; set; }
        public string errormessage { get; set; }
        public string computername { get; set; }
        public string inputcommand { get; set; }
        public string OutParameters { get; set; }
        public string LogData { get; set; }
        public string SourceTransactionId { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<bool> IsNotified { get; set; }
        public string NotificationRemarks { get; set; }
    }
}
