//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemanticCategory
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public int CategoryId { get; set; }
        public string SemanticClusterId { get; set; }
        public string SemanticClusterName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Timestamp { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
