//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int CompanyId { get; set; }
        public string Alias { get; set; }
        public int Role { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsDL { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<bool> IsActiveGroup { get; set; }
    }
}
