//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity.PostgreSql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntity : DbContext
    {
        public DataEntity()
            : base("name=DataEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<ActiveRegisteredNodes> ActiveRegisteredNodes { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryWorkflowMap> CategoryWorkflowMap { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<ExportConfigurationMaster> ExportConfigurationMasters { get; set; }
        public virtual DbSet<ExportJobProcessingHistory> ExportJobProcessingHistories { get; set; }
        public virtual DbSet<ExportScriptConfigurationDetail> ExportScriptConfigurationDetails { get; set; }
        public virtual DbSet<ExportServerDetail> ExportServerDetails { get; set; }
        public virtual DbSet<ExportSourceTargetMapping> ExportSourceTargetMappings { get; set; }
        public virtual DbSet<ExportTargetSystemDetail> ExportTargetSystemDetails { get; set; }
        public virtual DbSet<ExportTransactionDetail> ExportTransactionDetails { get; set; }
        public virtual DbSet<FailedNode> FailedNodes { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupAccess> GroupAccess { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<ObjectModelMaster> ObjectModelMasters { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<ReferenceData> ReferenceData { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ScheduledRequest> ScheduledRequest { get; set; }
        public virtual DbSet<ScheduledRequestActivities> ScheduledRequestActivities { get; set; }
        public virtual DbSet<Script> Script { get; set; }
        public virtual DbSet<ScriptExecuteRequest> ScriptExecuteRequest { get; set; }
        public virtual DbSet<ScriptInstance> ScriptInstances { get; set; }
        public virtual DbSet<ScriptParams> ScriptParams { get; set; }
        public virtual DbSet<SemanticCategory> SemanticCategory { get; set; }
        public virtual DbSet<SemanticCluster> SemanticCluster { get; set; }
        public virtual DbSet<SemanticNodeCluster> SemanticNodeCluster { get; set; }
        public virtual DbSet<SuperAdmin> SuperAdmin { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<TransactionInstance> TransactionInstance { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WorkflowCategoryMaster> WorkflowCategoryMaster { get; set; }
        public virtual DbSet<WorkflowMaster> WorkflowMaster { get; set; }
        public virtual DbSet<WorkflowParams> WorkflowParams { get; set; }
        public virtual DbSet<WorkflowTrackingDetails> WorkflowTrackingDetails { get; set; }
        public virtual DbSet<WorkflowTrackingMaster> WorkflowTrackingMaster { get; set; }
        public virtual DbSet<RegisterredNodes> RegisterredNodes { get; set; }
        public virtual DbSet<ScriptExecuteResponse> ScriptExecuteResponse { get; set; }
    }
}
