//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowTrackingMaster
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public System.DateTime Timestamp { get; set; }
        public System.Guid WorkflowId { get; set; }
        public int WorkflowVer { get; set; }
        public System.Guid InstanceId { get; set; }
        public string State { get; set; }
        public string StatusDescription { get; set; }
        public string RequestorId { get; set; }
        public string RequestorSourceIP { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public string RunAtIPAddress { get; set; }
        public string RunAtMachineName { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
