//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntity : DbContext
    {
        public DataEntity()
            : base("name=DataEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<CategoryWorkflowMap> CategoryWorkflowMap { get; set; }
        public DbSet<ObjectModelMaster> ObjectModelMaster { get; set; }
        public DbSet<Organization> Organization { get; set; }
        public DbSet<ScriptInstance> ScriptInstance { get; set; }
        public DbSet<Track> Track { get; set; }
        public DbSet<WorkflowCategoryMaster> WorkflowCategoryMaster { get; set; }
        public DbSet<WorkflowTrackingDetails> WorkflowTrackingDetails { get; set; }
        public DbSet<WorkflowTrackingMaster> WorkflowTrackingMaster { get; set; }
        public DbSet<GroupAccess> GroupAccess { get; set; }
        public DbSet<Type> Type { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<SuperAdmin> SuperAdmin { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<RegisterredNodes> RegisterredNodes { get; set; }
        public DbSet<ActiveRegisteredNodes> ActiveRegisteredNodes { get; set; }
        public DbSet<WorkflowParams> WorkflowParams { get; set; }
        public DbSet<Module> Module { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<SemanticCluster> SemanticCluster { get; set; }
        public DbSet<Companies> Companies { get; set; }
        public DbSet<ScheduledRequest> ScheduledRequest { get; set; }
        public DbSet<ScheduledRequestActivities> ScheduledRequestActivities { get; set; }
        public DbSet<SemanticCategory> SemanticCategory { get; set; }
        public DbSet<ScriptParams> ScriptParams { get; set; }
        public DbSet<SemanticNodeCluster> SemanticNodeCluster { get; set; }
        public DbSet<TransactionInstance> TransactionInstance { get; set; }
        public DbSet<WorkflowMaster> WorkflowMaster { get; set; }
        public DbSet<ExportJobProcessingHistory> ExportJobProcessingHistories { get; set; }
        public DbSet<ExportScriptConfigurationDetail> ExportScriptConfigurationDetails { get; set; }
        public DbSet<ExportTargetSystemDetail> ExportTargetSystemDetails { get; set; }
        public DbSet<ExportServerDetail> ExportServerDetails { get; set; }
        public DbSet<ExportTransactionDetail> ExportTransactionDetails { get; set; }
        public DbSet<ExportConfigurationMaster> ExportConfigurationMasters { get; set; }
        public DbSet<ExportSourceTargetMapping> ExportSourceTargetMappings { get; set; }
        public DbSet<Script> Script { get; set; }
        public DbSet<ReferenceData> ReferenceData { get; set; }
        public DbSet<ScriptExecuteRequest> ScriptExecuteRequest { get; set; }
        public DbSet<ScriptExecuteResponse> ScriptExecuteResponse { get; set; }
    }
}
