//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.WEM.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowTrackingDetails
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<System.Guid> WorkflowInstanceId { get; set; }
        public Nullable<decimal> ActivityStepCount { get; set; }
        public string ActivityId { get; set; }
        public string ActivityDisplayName { get; set; }
        public string ActivityParameters { get; set; }
        public string ActivityState { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.DateTime> EndedOn { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
